export { ReactComponent as Close } from './assets/close.svg'
export { ReactComponent as Twitter } from './assets/twitter.svg'
export { ReactComponent as Discord } from './assets/discord.svg'
export { ReactComponent as Outside } from './assets/outside.svg'
export { ReactComponent as Trash } from './assets/trash.svg'
export { ReactComponent as Arrow } from './assets/arrow.svg'
